config/routes.rb
Recipes::Application.routes.draw do

  devise_for :users

  root :to => "dashboard#index"

  namespace :manage do
    resources :recipes do
      resources :ingredients
      resources :steps
    end
  end

  resources :recipes, :only => [ :index ]
  scope ":username" do
    resources :recipes, :only => [ :show, :index ]
  end

end

app/models/food_item.rb
class FoodItem < ActiveRecord::Base
  has_many :ingredients
  has_many :recipes, :through => :ingredients
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  include SectionValidation
  include RankedModel

  belongs_to :recipe
  belongs_to :food_item
  belongs_to :section
  belongs_to :measure

  validates_presence_of :recipe_id, :text
  validates_length_of :text, :within => 5..256
  validates_length_of :extra_information, :maximum => 512
  validates_uniqueness_of :food_item_id, :scope => :recipe_id

  before_validation :parse_text

  validate :validate_section_relationship

  attr_protected :food_item_id, :measure_id, :quantity

  ranks :sort, :with_same => :recipe_id

  scope :unsectioned, where(:section_id => nil)

  def measure=(units_text)
    self.measure_id = Measure.find_or_create_by_name(units_text).id
  end

  def food_item=(food_item_text)
    self.food_item_id = FoodItem.find_or_create_by_name(food_item_text).id
  end

  def parsed?
    self.food_item.present? && (self.measure.present? || self.quantity.present?)
  end

  private

  #TODO refactor this method
  def parse_text
    IngredientParser.new(self.text).tap do |ip|

      self.food_item         = ip.food_item if ip.food_item
      self.extra_information = ip.extra_information if ip.extra_information

      #FIXME before assigning, convert fractions to decimals
      if supplied = Measure.find_by_name(ip.measure) and supplied.is_convertible?
        [ip.quantity, ip.measure].join(" ").convert_to(supplied.convert_to).tap do |converted|
          self.measure  = converted.units
          self.quantity = converted.scalar
        end
      else
        self.quantity = ip.quantity
        self.measure  = ip.measure
      end

    end
  end

end

app/models/measure.rb
class Measure < ActiveRecord::Base
  has_many :ingredients

  validates_length_of :name, :within => 1..32

  attr_protected :measure_type

  STANDARD_UNITS = { :mass => "g", :volume => "ml" }

  def convert_to
    raise ConversionError, "#{self.name} is not a convertible measure" unless self.measure_type
    Measure.find_by_name(STANDARD_UNITS[self.measure_type.to_sym]).name
  end

  def is_convertible?
    self.measure_type and self.name != STANDARD_UNITS[self.measure_type.to_sym]
  end

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base

  extend FriendlyId

  friendly_id :title, :use => [ :slugged, :scoped ], :scope => :user

  has_many :food_items, :through => :ingredients
  has_many :sections, :order => "sort asc"
  has_many :steps, :order => "sort asc"
  has_many :ingredients, :order => "sort asc"
  belongs_to :user

  validates_presence_of :user_id
  validates_numericality_of :preparation_time, :allow_nil => true
  validates_numericality_of :cooking_time, :allow_nil => true
  validates_inclusion_of :cooking_time, :in => 1..600, :allow_nil => true
  validates_inclusion_of :inactive_preparation_time, :in => 1..2880, :allow_nil => true
  validates_inclusion_of :preparation_time, :in => 1..600, :allow_nil => true
  validates_length_of :title, :within => 3..128

  attr_protected :user_id, :state

  attr_accessor :preparation_time_units, :cooking_time_units

  accepts_nested_attributes_for :ingredients, :reject_if => :all_blank
  accepts_nested_attributes_for :steps, :reject_if => :all_blank
  accepts_nested_attributes_for :sections, :reject_if => :all_blank

  scope :published, where(:state => :published)

  state_machine :initial => :initialised do

    event :initial_edit do
      transition :initialised => :in_progress
    end

    event :publish do
      transition :in_progress => :published
    end

  end

end

app/models/section.rb
class Section < ActiveRecord::Base
  include RankedModel

  belongs_to :recipe
  has_many :ingredients
  has_many :steps

  validates_length_of :name, :within => 2..128
  validates_numericality_of :sort

  ranks :sort, :with_same => :recipe_id
end

app/models/step.rb
class Step < ActiveRecord::Base
  include SectionValidation
  include RankedModel

  belongs_to :recipe
  belongs_to :section

  validates_presence_of :text
  validates_presence_of :recipe
  validates_numericality_of :sort, :allow_nil => true
  validate :validate_section_relationship

  ranks :sort, :with_same => :recipe_id

  scope :unsectioned, where(:section_id => nil)

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :username, :email, :password, :password_confirmation, :remember_me

  has_many :recipes

  def to_param
    username
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
    @recipes = Recipe.published

    respond_to do |format|
      format.html
      format.xml
    end
  end

  def show
    @recipe = Recipe.published.find(params[:id])

    respond_to do |format|
      format.html
      format.xml
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def title(page_title)
    content_for(:title) { page_title }
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper

  def display_ingredient(ingredient)
    render_ingredient_line_partial(ingredient)
  end

  private

  def render_ingredient_line_partial(ingredient)

    ingredient_lines_path = "/shared/ingredients"

    # TODO this can be made nicer
    if ingredient.quantity and ingredient.measure and ingredient.food_item
      render :partial => File.join(ingredient_lines_path, "quantity_measure_and_food_item"), :locals => { :ingredient => ingredient}
    elsif ingredient.quantity and ingredient.food_item
      render :partial => File.join(ingredient_lines_path, "quantity_and_food_item"), :locals => { :ingredient => ingredient}
    elsif ingredient.measure and ingredient.food_item
      render :partial => File.join(ingredient_lines_path, "measure_and_food_item"), :locals => { :ingredient => ingredient}
    else
      render :partial => File.join(ingredient_lines_path, "default"), :locals => { :ingredient => ingredient}
    end
  end

end

app/helpers/navigation_helper.rb
module NavigationHelper

  def navigation_tabs
    capture_haml do
      haml_tag(:ul, :class => "primary") do
        NAVIGATION_CONFIG.each do |tab|
          tab_content(tab)
        end
      end
    end
  end

  private

  def tab_content(tab, opts={})
    opts.merge! :class => tab["label"]

    return if tab["logged_in"] and not current_user

    if tab["controller_path"] == controller.controller_path
      haml_tag :li, tab["label"], opts.merge({ :class => "active" })
    else
      haml_tag :li, link_to(tab["label"], send(tab["path"])), opts
    end
  end

end

app/helpers/recipes_helper.rb
module RecipesHelper

  def options_for_time_select
    { :minutes => 1, :hours => 60, :days => 1440 }
  end

end

app/helpers/steps_helper.rb
module StepsHelper
end

app/views/dashboard/index.html.haml
%section

  #main

    %h1 My money's in that office, right?

    %p
      My money's in that office, right? If she start giving me some bullshit about it ain't there, and we got to go someplace else and get it, I'm 
      = link_to 'gonna', '#'
      shoot you in the head then and there. Then I'm gonna shoot that bitch in the kneecaps, find out where my goddamn money is. She gonna tell me too. Hey, look at me when I'm talking to you, motherfucker. You listen: we go in there, and that nigga Winston or anybody else is in there, you the first motherfucker to get shot. You understand?

    %ul
      %li Pulp Fiction
      %li Reservoir Dogs

    %p
      Your bones don't break, mine do. That's clear. Your cells react to bacteria and viruses differently than mine. You don't get sick, I do. That's also clear. But for some reason, you and I react the exact same way to water. We swallow it too fast, we choke. We get some in our lungs, we drown. However unreal it may seem, we are connected, you and I. We're on the same curve, just on opposite ends.

    %h1 Your bones don't break, mine do.
    %p
      My money's in that office, right? If she start giving me some bullshit about it ain't there, and we got to go someplace else and get it, I'm gonna shoot you in the head then and there. Then I'm gonna shoot that bitch in the kneecaps, find out where my goddamn money is. She gonna tell me too. Hey, look at me when I'm talking to you, motherfucker. You listen: we go in there, and that nigga Winston or anybody else is in there, you the first motherfucker to get shot. You understand?

    %p
      Your bones don't break, mine do. That's clear. Your cells react to bacteria and viruses differently than mine. You don't get sick, I do. That's also clear. But for some reason, you and I react the exact same way to water. We swallow it too fast, we choke. We get some in our lungs, we drown. However unreal it may seem, we are connected, you and I. We're on the same curve, just on opposite ends.


#right-sidebar
  #five-random-recipes.sidebar-section
    %h1 5 random recipes
    %ul
      %li Chocolate Cola Cake
      %li Mother's Cheese And Onion Pie
      %li Lamb Kebabs
      %li Beef fajitas with guacamole, refried beans and tomato salsa
      %li Salt Cod and Tomato Stew

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    =stylesheet_link_tag "base"
    %meta{:charset => "utf-8"}
    %title= yield(:title)
  %body
    =render "shared/standard_header"
    #content
      =yield
    %footer
      %p footer content to go here

app/views/recipes/_filter.html.haml
#filter.sidebar-section
  %h1
    Filter
  %form
    =check_box_tag "veg"
    =label_tag "veg", "Vegetarian"
    =check_box_tag "nuts"
    =label_tag "nuts", "Contains Nuts"

app/views/recipes/_links.html.haml
%ul
  %li
    =link_to "create", new_manage_recipe_path

app/views/recipes/index.html.haml
- title "Listing recipes"
#main
  %section#recipe_list
    %ul
    - @recipes.each do |r|
      %li
        = link_to r.title, recipe_path( :username => r.user, :id => r)

#right-sidebar
  =render "links"
  =render "filter"

app/views/recipes/index.xml.haml
!!! XML
%recipes
  - @recipes.each do |recipe|
    %recipe
      %title
        = recipe.title

app/views/recipes/show.html.haml
%h1
  = @recipe.title

#ingredients
  %ul
    - @recipe.ingredients.each do |i|
      %li= display_ingredient(i)

app/views/shared/_standard_header.html.haml
%header
  %h1 culinarian
  #login
    You are currently logged in as Nobody
  %nav
    =navigation_tabs

app/views/shared/ingredients/_default.html.haml
=ingredient.text

app/views/shared/ingredients/_measure_and_food_item.html.haml
%span.unit
  =ingredient.measure.name
of
%span.fooditem
  =ingredient.food_item.name

app/views/shared/ingredients/_quantity_and_food_item.html.haml
%span.quantity
  =ingredient.quantity
%span.fooditem
  =ingredient.food_item.name.pluralize

app/views/shared/ingredients/_quantity_measure_and_food_item.html.haml
%span.quantity
  =ingredient.quantity
%span.measure
  =ingredient.measure.name
of
%span.fooditem
  =ingredient.food_item.name